### ISSUE TITLE
`flask init-db` hits constraints on heroku/postgresdb

### ISSUE THREAD

**Issue by thadk** [codefordc/us-congress-pizza-flag-tracker#86]
I got the heroku running with a few minor tweaks. The next issue I encountered and wasn't able to address was this one. Let me know if you have any ideas @rajindermavi:

```
$ heroku run flask init-db
Running flask init-db on ⬢ codefordc-flag... up, run.3260 (Free)
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 951, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/app/.heroku/python/lib/python3.8/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.ForeignKeyViolation: insert or update on table "status" violates foreign key constraint "status_status_federal_office_code_fkey"
DETAIL:  Key (status_federal_office_code)=(HOSS) is not present in table "offices".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/init_db.py", line 51, in init_db_command
    init_db()
  File "/app/init_db.py", line 44, in init_db
    db.session.commit()
  File "<string>", line 2, in commit
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3340, in flush
    self._flush(objects)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3480, in _flush
    transaction.rollback(_capture_exception=True)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3440, in _flush
    flush_context.execute()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 951, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/app/.heroku/python/lib/python3.8/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "status" violates foreign key constraint "status_status_federal_office_code_fkey"
DETAIL:  Key (status_federal_office_code)=(HOSS) is not present in table "offices".

[SQL: INSERT INTO status (id, status_federal_office_code, sequence_num, description) VALUES (%(id)s, %(status_federal_office_code)s, %(sequence_num)s, %(description)s)]
[parameters: ({'id': 1, 'status_federal_office_code': 'HOSS', 'sequence_num': 1, 'description': 'Constituent request in'}, {'id': 2, 'status_federal_office_code': 'HOSS', 'sequence_num': 2, 'description': 'HOSS verified as printed and scanned physical QR code'}, {'id': 3, 'status_federal_office_code': 'AOC', 'sequence_num': 3, 'description': 'AOC received flag from HOSS'}, {'id': 4, 'status_federal_office_code': 'AOC', 'sequence_num': 4, 'description': 'AOC has flown flag and added certificate'}, {'id': 5, 'status_federal_office_code': 'MAIL', 'sequence_num': 5, 'description': 'Mail Services picked up flag from AOC'}, {'id': 6, 'status_federal_office_code': 'STATE', 'sequence_num': 6, 'description': 'Congressional Staffer received flag'}, {'id': 7, 'status_federal_office_code': 'STATE', 'sequence_num': 7, 'description': 'Staffer order closed (Flag ready for shipment)'}, {'id': 8, 'status_federal_office_code': 'STATE', 'sequence_num': 8, 'description': 'Constituent notified'}, {'id': 9, 'status_federal_office_code': 'ALL', 'sequence_num': 9, 'description': 'Order canceled'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)```

**Comment by thadk** [comment]
Got farther when I wiped and recreated the migrations folder:
```
(base) Thads-MBP:flagpizza thadkerosky$ heroku run flask db upgrade
Running flask db upgrade on ⬢ codefordc-flag... up, run.9767 (Free)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 50e1de6431bf, empty message
(base) Thads-MBP:flagpizza thadkerosky$ heroku run flask init-db
Running flask init-db on ⬢ codefordc-flag... up, run.3865 (Free)
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/init_db.py", line 59, in init_db_command
    init_db()
  File "/app/init_db.py", line 40, in init_db
    init_user_table_state_users(office_codes_list, db)
  File "/app/initial_data/init_user_table.py", line 30, in init_user_table_state_users
    UserActions.create(params)
  File "/app/UserActions.py", line 33, in create
    db.session.commit()
  File "<string>", line 2, in commit
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3340, in flush
    self._flush(objects)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3480, in _flush
    transaction.rollback(_capture_exception=True)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3440, in _flush
    flush_context.execute()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(100)

[SQL: INSERT INTO users (username, password, office_code, can_update_status_for, can_update_password_for, can_create_update_delete_orders, is_admin) VALUES (%(username)s, %(password)s, %(office_code)s, %(can_update_status_for)s, %(can_update_password_for)s, %(can_create_update_delete_orders)s, %(is_admin)s)]
[parameters: {'username': 'AK-01-ADMIN', 'password': b'$2b$10$BgxjkYzWWWdsZMiQojjG0eHwBfuFXW0f7doKP5MSPMUCVhhcNx5fW', 'office_code': 'AK-01', 'can_update_status_for': 'AK-01', 'can_update_password_for': 'AK-01', 'can_create_update_delete_orders': 'N', 'is_admin': 'N'}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
```

**Comment by thadk** [comment]
Back to the original error now that the password field has been extended:
@rajindermavi, any ideas?
I improved the instructions for how to replicate below:

```
$ heroku login
$ heroku git:remote -a codefordc-flag
$ git push heroku
(reset DB in Heroku app under resources=>postgres=>settings=>reset=>yes, type name of app)
$ heroku run flask db upgrade
$ heroku run flask db upgrade

Running flask init-db on ⬢ codefordc-flag... up, run.5755 (Free)
DB is in debug mode: True
DB is in mode: development
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 951, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/app/.heroku/python/lib/python3.8/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.ForeignKeyViolation: insert or update on table "status" violates foreign key constraint "status_status_federal_office_code_fkey"
DETAIL:  Key (status_federal_office_code)=(HOSS) is not present in table "offices".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/init_db.py", line 59, in init_db_command
    init_db()
  File "/app/init_db.py", line 52, in init_db
    db.session.commit()
  File "<string>", line 2, in commit
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3340, in flush
    self._flush(objects)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3480, in _flush
    transaction.rollback(_capture_exception=True)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3440, in _flush
    flush_context.execute()
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 951, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/app/.heroku/python/lib/python3.8/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "status" violates foreign key constraint "status_status_federal_office_code_fkey"
DETAIL:  Key (status_federal_office_code)=(HOSS) is not present in table "offices".

[SQL: INSERT INTO status (id, status_federal_office_code, sequence_num, description) VALUES (%(id)s, %(status_federal_office_code)s, %(sequence_num)s, %(description)s)]
[parameters: ({'id': 1, 'status_federal_office_code': 'HOSS', 'sequence_num': 1, 'description': 'Constituent request in'}, {'id': 2, 'status_federal_office_code': 'HOSS', 'sequence_num': 2, 'description': 'HOSS verified as printed and scanned physical QR code'}, {'id': 3, 'status_federal_office_code': 'AOC', 'sequence_num': 3, 'description': 'AOC received flag from HOSS'}, {'id': 4, 'status_federal_office_code': 'AOC', 'sequence_num': 4, 'description': 'AOC has flown flag and added certificate'}, {'id': 5, 'status_federal_office_code': 'MAIL', 'sequence_num': 5, 'description': 'Mail Services picked up flag from AOC'}, {'id': 6, 'status_federal_office_code': 'STATE', 'sequence_num': 6, 'description': 'Congressional Staffer received flag'}, {'id': 7, 'status_federal_office_code': 'STATE', 'sequence_num': 7, 'description': 'Staffer order closed (Flag ready for shipment)'}, {'id': 8, 'status_federal_office_code': 'STATE', 'sequence_num': 8, 'description': 'Constituent notified'}, {'id': 9, 'status_federal_office_code': 'ALL', 'sequence_num': 9, 'description': 'Order canceled'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```
